apiVersion: v1
kind: Secret
metadata:
  name: cb-file-hosting-config
  namespace: {{ default "clearblade" .Values.global.namespace }}
data:
  hmac_secret.txt: |
{{ .Values.global.fileHostingHmacSecret }}