apiVersion: v1
kind: Service
metadata:
  name: cb-tiles-service
  namespace: {{ default "clearblade" .Values.global.namespace }}
spec:
  ports:
  - name: tiles
    targetPort: 7777
    port: 7777
    protocol: TCP
  selector:
    app: cb-tiles